name: car_shop
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  get_cli: ^1.6.0
  device_preview: ^0.7.4
  badges: ^2.0.1
  flutter_image_slideshow: ^0.1.1
  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0
 
  responsive_grid: ^2.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - lib/Assets/RES/
  # fonts:
  #   - family: Cairo-Bold
  #     fonts:
  #       - asset: lib/Assets/Fonts/Cairo-Bold.ttf

  #   - family: Cairo-Regular
  #     fonts:
  #       - asset: lib/Assets/Fonts/Cairo-Regular.ttf

  #   - family: Cairo-SemiBold
  #     fonts:
  #       - asset: lib/Assets/Fonts/SemiBold.ttf